### ISSUE TITLE
Cloud Init Causing Issues With etc/hosts

### ISSUE THREAD

**Issue by bgilkes** [linuxone-community-cloud/tickets#53]
<p><strong>Name:</strong><br />
Scott Fryer</p>

<p><strong>Email:</strong><br />
scfryer@redhat.com</p>

<p><strong>Open Source Community:</strong><br />
Adoptium</p>

<p><strong>IP Addresses:</strong><br />
148.100.75.212 <br />148.100.74.54 <br />148.100.74.237 <br />148.100.74.92 <br />148.100.74.2 <br />148.100.74.193 <br />148.100.74.154 <br />148.100.74.240 <br />148.100.74.105 <br />148.100.74.163 <br />148.100.74.16 <br />148.100.74.223</p>

<p><strong>Issue:</strong><br />
As per this EF issue ( https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2169 ) and in particular this comment https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2169#note_1140917 , in summary.. <br /> <br />We have some issues caused by changes being made to /etc/hosts, which we believe is caused by cloud-init and particularly one line in user-data: <br /> <br />manage_etc_hosts: "localhost" <br /> <br />I think the best way to deal with it would be to remove that line from userdata as without it, every redeployment of VM will bring the issue again. The line should be deleted from user-data or set to: <br /> <br />manage_etc_hosts: "false" <br /> <br />Thanks</p>

**Comment by chee-ip** [comment]
It has been updated and on production now.

**Comment by bgilkes** [comment]
I am closing this ticket based on the resolution provided.  Please reopen if there are other issues.
